<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWindowsDesktopSdk>true</UseWindowsDesktopSdk>
    <RootNamespace>TPFan.Shared</RootNamespace>
    <AssemblyName>TPFan.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="4.7.0" />
  </ItemGroup>

</Project>
